var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/curated-images/route.js")
R.c("server/chunks/[root-of-the-server]__05um6g_._.js")
R.c("server/chunks/node_modules_@supabase_0vm.sn3._.js")
R.c("server/chunks/node_modules_next_dist_esm_build_templates_app-route_0rx-24u.js")
R.c("server/chunks/node_modules_0ykeg.h._.js")
R.c("server/chunks/[root-of-the-server]__0nglzhr._.js")
R.c("server/chunks/node_modules_@google_generative-ai_dist_index_mjs_07lt0._._.js")
R.c("server/chunks/_next-internal_server_app_api_curated-images_route_actions_0cva8yq.js")
R.m(70483)
module.exports=R.m(70483).exports
