var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/seo/[slug]/page.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0rg02q3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0h5tz8r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0~7ngm4.js")
R.c("server/chunks/ssr/[root-of-the-server]__10914~~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.angw.._.js")
R.c("server/chunks/ssr/node_modules_100_dhq._.js")
R.c("server/chunks/ssr/_0gyit03._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_seo_[slug]_page_actions_0tu6m-h.js")
R.m(83545)
module.exports=R.m(83545).exports
