/**
 * CAD Engine Service
 * Generates 3D designs and technical drawings from brief
 * 100% free, uses local calculations and Three.js
 */

export interface DesignBrief {
  itemType: string; // chair, table, bed, wardrobe, etc.
  style: string; // modern, classic, minimal, etc.
  dimensions: {
    length: number;
    width: number;
    height: number;
    unit: 'cm' | 'inch';
  };
  materials: string[];
  features: string[];
  budget?: number;
  notes?: string;
}

export interface DesignOutput {
  designId: string;
  name: string;
  description: string;
  specifications: DesignSpecifications;
  threeDData: ThreeDModelData;
  technicalDrawings: TechnicalDrawing[];
  materialsList: MaterialRequirement[];
  estimatedCost: CostEstimate;
  images: string[]; // Preview image URLs
}

export interface DesignSpecifications {
  dimensions: {
    length: number;
    width: number;
    height: number;
    unit: string;
  };
  weight: number;
  loadCapacity?: number;
  finish: string;
  assemblyTime: number; // minutes
  skillLevel: 'beginner' | 'intermediate' | 'advanced';
}

export interface ThreeDModelData {
  format: 'threejs' | 'obj' | 'glb';
  vertices: number[][];
  faces: number[][];
  uvs: number[][];
  normals: number[][];
  materials: MaterialDefinition[];
}

export interface MaterialDefinition {
  id: string;
  name: string;
  color: string;
  roughness: number;
  metalness: number;
  texture?: string;
}

export interface TechnicalDrawing {
  type: 'front' | 'side' | 'top' | 'isometric' | 'exploded';
  viewName: string;
  svgData: string;
  dimensions: DrawingDimension[];
}

export interface DrawingDimension {
  label: string;
  value: number;
  position: { x: number; y: number };
}

export interface MaterialRequirement {
  material: string;
  quantity: number;
  unit: string;
  notes?: string;
}

export interface CostEstimate {
  materials: number;
  labor: number;
  overhead: number;
  total: number;
  currency: string;
}

export class CADEngineService {
  /**
   * Generate 3D design from brief
   */
  async generateDesign(brief: DesignBrief): Promise<DesignOutput> {
    const designId = `design-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    
    // Generate specifications based on brief
    const specifications = this.calculateSpecifications(brief);
    
    // Generate 3D model data
    const threeDData = this.generateThreeDModel(brief);
    
    // Generate technical drawings
    const technicalDrawings = this.generateTechnicalDrawings(brief);
    
    // Calculate materials needed
    const materialsList = this.calculateMaterials(brief);
    
    // Estimate cost
    const estimatedCost = this.estimateCost(brief, materialsList);

    return {
      designId,
      name: this.generateDesignName(brief),
      description: this.generateDescription(brief),
      specifications,
      threeDData,
      technicalDrawings,
      materialsList,
      estimatedCost,
      images: [] // Would be generated by image generation service
    };
  }

  /**
   * Generate design name
   */
  private generateDesignName(brief: DesignBrief): string {
    const stylePrefix = {
      'modern': 'Modern',
      'classic': 'Classic',
      'minimal': 'Minimal',
      'industrial': 'Industrial',
      'bohemian': 'Bohemian',
      'scandinavian': 'Scandinavian'
    }[brief.style.toLowerCase()] || 'Custom';

    const itemTypeName = brief.itemType.charAt(0).toUpperCase() + brief.itemType.slice(1);
    
    return `${stylePrefix} ${itemTypeName}`;
  }

  /**
   * Generate design description
   */
  private generateDescription(brief: DesignBrief): string {
    const features = brief.features.join(', ');
    const materials = brief.materials.join(' and ');
    
    return `A ${brief.style} ${brief.itemType} designed with ${materials}. ` +
           `Features include ${features}. ` +
           `Dimensions: ${brief.dimensions.length}x${brief.dimensions.width}x${brief.dimensions.height} ${brief.dimensions.unit}.`;
  }

  /**
   * Calculate detailed specifications
   */
  private calculateSpecifications(brief: DesignBrief): DesignSpecifications {
    // Calculate volume
    const volume = (brief.dimensions.length * brief.dimensions.width * brief.dimensions.height) / 1000000; // m³
    
    // Estimate weight (wood average: 600 kg/m³)
    const weight = volume * 600 * 1.2; // 20% for hardware
    
    // Assembly time based on complexity
    const baseTime = {
      'chair': 30,
      'table': 60,
      'bed': 90,
      'wardrobe': 120,
      'desk': 75,
      'cabinet': 90,
      'bookshelf': 60,
      'nightstand': 45
    }[brief.itemType.toLowerCase()] || 60;

    const complexityMultiplier = brief.features.length * 0.2 + 1;
    const assemblyTime = Math.round(baseTime * complexityMultiplier);

    // Skill level
    const skillLevel = assemblyTime > 90 ? 'advanced' : assemblyTime > 60 ? 'intermediate' : 'beginner';

    return {
      dimensions: {
        length: brief.dimensions.length,
        width: brief.dimensions.width,
        height: brief.dimensions.height,
        unit: brief.dimensions.unit
      },
      weight: Math.round(weight * 10) / 10,
      loadCapacity: this.estimateLoadCapacity(brief.itemType),
      finish: brief.materials.includes('wood') ? 'Varnish' : 'Paint',
      assemblyTime,
      skillLevel
    };
  }

  /**
   * Estimate load capacity based on item type
   */
  private estimateLoadCapacity(itemType: string): number | undefined {
    const capacities: Record<string, number> = {
      'chair': 120,
      'table': 100,
      'bed': 200,
      'wardrobe': 50,
      'desk': 80,
      'bookshelf': 30
    };
    return capacities[itemType.toLowerCase()];
  }

  /**
   * Generate 3D model data
   */
  private generateThreeDModel(brief: DesignBrief): ThreeDModelData {
    const { length, width, height } = brief.dimensions;
    
    // Generate simple box geometry (in production, this would be more complex)
    const halfL = length / 2;
    const halfW = width / 2;
    const halfH = height / 2;

    // 8 vertices of a box
    const vertices = [
      [-halfL, -halfW, -halfH], // 0
      [halfL, -halfW, -halfH],   // 1
      [halfL, halfW, -halfH],    // 2
      [-halfL, halfW, -halfH],   // 3
      [-halfL, -halfW, halfH],   // 4
      [halfL, -halfW, halfH],    // 5
      [halfL, halfW, halfH],     // 6
      [-halfL, halfW, halfH]     // 7
    ];

    // 12 faces (triangles)
    const faces = [
      // Bottom
      [0, 1, 2], [0, 2, 3],
      // Top
      [4, 5, 6], [4, 6, 7],
      // Front
      [3, 2, 6], [3, 6, 7],
      // Back
      [0, 1, 5], [0, 5, 4],
      // Left
      [0, 3, 7], [0, 7, 4],
      // Right
      [1, 2, 6], [1, 6, 5]
    ];

    // Simple UV mapping
    const uvs = vertices.map(() => [0.5, 0.5]);

    // Calculate normals
    const normals = vertices.map(() => [0, 0, 1]);

    // Materials
    const materials: MaterialDefinition[] = brief.materials.map((mat, i) => ({
      id: `mat-${i}`,
      name: mat,
      color: this.getMaterialColor(mat),
      roughness: 0.5,
      metalness: mat.toLowerCase().includes('metal') ? 0.8 : 0.1
    }));

    return {
      format: 'threejs',
      vertices,
      faces,
      uvs,
      normals,
      materials
    };
  }

  /**
   * Get approximate color for material
   */
  private getMaterialColor(material: string): string {
    const colors: Record<string, string> = {
      'beech': '#D2B48C',
      'oak': '#C19A6B',
      'walnut': '#5D4E37',
      'pine': '#F5DEB3',
      'mahogany': '#C04000',
      'birch': '#E3DAC9',
      'cherry': '#A0522D',
      'maple': '#F0E68C',
      'mdf': '#F5F5DC',
      'plywood': '#DEB887',
      'metal': '#A9A9A9',
      'steel': '#C0C0C0',
      'aluminum': '#D3D3D3',
      'glass': '#E0FFFF',
      'fabric': '#FFE4E1',
      'leather': '#8B4513'
    };

    const lowerMat = material.toLowerCase();
    return colors[lowerMat] || '#D2B48C';
  }

  /**
   * Generate technical drawings (SVG data)
   */
  private generateTechnicalDrawings(brief: DesignBrief): TechnicalDrawing[] {
    const { length, width, height } = brief.dimensions;
    const views: TechnicalDrawing['type'][] = ['front', 'side', 'top', 'isometric'];

    return views.map(view => ({
      type: view,
      viewName: this.getViewName(view),
      svgData: this.generateSVG(view, brief),
      dimensions: this.getDrawingDimensions(view, brief)
    }));
  }

  private getViewName(view: string): string {
    const names: Record<string, string> = {
      'front': 'المنظر الأمامي',
      'side': 'المنظر الجانبي',
      'top': 'المنظر العلوي',
      'isometric': 'المنظر ثلاثي الأبعاد',
      'exploded': 'المنظر المنفجر'
    };
    return names[view] || view;
  }

  /**
   * Generate SVG for a view
   */
  private generateSVG(view: string, brief: DesignBrief): string {
    const { length, width, height } = brief.dimensions;
    const w = 400;
    const h = 300;

    // Simple box representation (in production, this would be more detailed)
    return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}">
      <rect x="50" y="50" width="${w - 100}" height="${h - 100}" 
            fill="#f0f0f0" stroke="#333" stroke-width="2"/>
      <text x="${w / 2}" y="30" text-anchor="middle" font-size="14">${this.getViewName(view)}</text>
      <text x="${w / 2}" y="${h - 20}" text-anchor="middle" font-size="10">
        ${view === 'front' || view === 'back' ? `${length} x ${height}` : 
          view === 'side' ? `${width} x ${height}` : 
          `${length} x ${width}`} ${brief.dimensions.unit}
      </text>
    </svg>`;
  }

  private getDrawingDimensions(view: string, brief: DesignBrief): DrawingDimension[] {
    const { length, width, height, unit } = brief.dimensions;

    if (view === 'front') {
      return [
        { label: 'W', value: length, position: { x: 200, y: 280 } },
        { label: 'H', value: height, position: { x: 20, y: 150 } }
      ];
    } else if (view === 'side') {
      return [
        { label: 'D', value: width, position: { x: 200, y: 280 } },
        { label: 'H', value: height, position: { x: 20, y: 150 } }
      ];
    } else if (view === 'top') {
      return [
        { label: 'W', value: length, position: { x: 200, y: 280 } },
        { label: 'D', value: width, position: { x: 380, y: 150 } }
      ];
    }

    return [];
  }

  /**
   * Calculate materials needed
   */
  private calculateMaterials(brief: DesignBrief): MaterialRequirement[] {
    const { length, width, height } = brief.dimensions;
    const volume = (length * width * height) / 1000000; // m³

    const materials: MaterialRequirement[] = [];

    // Primary materials
    for (const material of brief.materials) {
      const isWood = !['metal', 'steel', 'aluminum', 'glass'].includes(material.toLowerCase());
      
      if (isWood) {
        materials.push({
          material: `${material} wood`,
          quantity: Math.ceil(volume * 1000 * 1.2), // 20% waste
          unit: 'board feet',
          notes: 'Including 20% waste allowance'
        });
      }
    }

    // Hardware
    materials.push({
      material: 'Screws and fasteners',
      quantity: Math.ceil(volume * 20),
      unit: 'pieces',
      notes: 'Various sizes'
    });

    materials.push({
      material: 'Wood glue',
      quantity: Math.ceil(volume * 0.5),
      unit: 'kg',
      notes: 'High strength'
    });

    // Finish materials
    const surfaceArea = 2 * (length * width + length * height + width * height) / 10000; // m²
    materials.push({
      material: 'Varnish/Paint',
      quantity: Math.ceil(surfaceArea * 0.3 * 2), // 2 coats
      unit: 'liters',
      notes: 'For 2 coats'
    });

    return materials;
  }

  /**
   * Estimate cost
   */
  private estimateCost(brief: DesignBrief, materials: MaterialRequirement[]): CostEstimate {
    // Material costs (EGP)
    const materialPrices: Record<string, number> = {
      'beech wood': 35,
      'oak wood': 50,
      'walnut wood': 80,
      'pine wood': 25,
      'Screws and fasteners': 2,
      'Wood glue': 50,
      'Varnish/Paint': 120
    };

    let materialsCost = 0;
    for (const mat of materials) {
      const price = materialPrices[mat.material] || 30;
      materialsCost += mat.quantity * price;
    }

    // Labor (8 hours average)
    const laborHours = 8;
    const laborRate = 100; // EGP/hour
    const laborCost = laborHours * laborRate;

    // Overhead (20%)
    const overheadCost = (materialsCost + laborCost) * 0.20;

    const total = materialsCost + laborCost + overheadCost;

    return {
      materials: Math.round(materialsCost),
      labor: laborCost,
      overhead: Math.round(overheadCost),
      total: Math.round(total),
      currency: 'EGP'
    };
  }

  /**
   * Export design to different formats
   */
  async exportDesign(designId: string, format: 'obj' | 'stl' | 'dxf' | 'pdf'): Promise<Buffer | null> {
    // In production, this would convert the 3D model to the requested format
    console.log(`[CAD] Exporting design ${designId} to ${format}`);
    return null;
  }
}

export const cadEngine = new CADEngineService();
