var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/furniture/[type]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mtjjko._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_06-6dut.js")
R.c("server/chunks/ssr/[root-of-the-server]__10914~~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.angw.._.js")
R.c("server/chunks/ssr/node_modules_100_dhq._.js")
R.c("server/chunks/ssr/_0gyit03._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_furniture_[type]_page_actions_0atnlkt.js")
R.m(45008)
module.exports=R.m(45008).exports
