// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin-gate" | "/admin-gate/cms" | "/admin-gate/login" | "/bookings" | "/dashboard" | "/dashboard/analytics" | "/dashboard/automation" | "/dashboard/billing" | "/dashboard/bookings" | "/dashboard/content-generator" | "/dashboard/cta" | "/dashboard/leads" | "/dashboard/media" | "/dashboard/navigation" | "/dashboard/pages" | "/dashboard/pages/edit/[id]" | "/dashboard/pages/new" | "/dashboard/seo" | "/dashboard/settings" | "/dashboard/tenants" | "/dashboard/theme" | "/elite" | "/elite/dashboard" | "/elite/login" | "/furniture" | "/furniture/[type]" | "/pages/[slug]" | "/privacy" | "/request" | "/room/[id]" | "/rooms" | "/rooms/[slug]" | "/seo/[slug]" | "/start" | "/terms"
type AppRouteHandlerRoutes = "/api/analytics" | "/api/auth/dev-login" | "/api/auth/recovery" | "/api/bookings" | "/api/bookings/[id]" | "/api/checkout" | "/api/cms/config" | "/api/cms/public-config" | "/api/cms/upload" | "/api/content-generator" | "/api/content-generator/improve" | "/api/leads" | "/api/media" | "/api/navigation" | "/api/pages" | "/api/pages/[id]" | "/api/pages/[id]/sections" | "/api/pexels" | "/api/tenant" | "/api/tenants" | "/api/theme"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin-gate" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin-gate": {}
  "/admin-gate/cms": {}
  "/admin-gate/login": {}
  "/api/analytics": {}
  "/api/auth/dev-login": {}
  "/api/auth/recovery": {}
  "/api/bookings": {}
  "/api/bookings/[id]": { "id": string; }
  "/api/checkout": {}
  "/api/cms/config": {}
  "/api/cms/public-config": {}
  "/api/cms/upload": {}
  "/api/content-generator": {}
  "/api/content-generator/improve": {}
  "/api/leads": {}
  "/api/media": {}
  "/api/navigation": {}
  "/api/pages": {}
  "/api/pages/[id]": { "id": string; }
  "/api/pages/[id]/sections": { "id": string; }
  "/api/pexels": {}
  "/api/tenant": {}
  "/api/tenants": {}
  "/api/theme": {}
  "/bookings": {}
  "/dashboard": {}
  "/dashboard/analytics": {}
  "/dashboard/automation": {}
  "/dashboard/billing": {}
  "/dashboard/bookings": {}
  "/dashboard/content-generator": {}
  "/dashboard/cta": {}
  "/dashboard/leads": {}
  "/dashboard/media": {}
  "/dashboard/navigation": {}
  "/dashboard/pages": {}
  "/dashboard/pages/edit/[id]": { "id": string; }
  "/dashboard/pages/new": {}
  "/dashboard/seo": {}
  "/dashboard/settings": {}
  "/dashboard/tenants": {}
  "/dashboard/theme": {}
  "/elite": {}
  "/elite/dashboard": {}
  "/elite/login": {}
  "/furniture": {}
  "/furniture/[type]": { "type": string; }
  "/pages/[slug]": { "slug": string; }
  "/privacy": {}
  "/request": {}
  "/room/[id]": { "id": string; }
  "/rooms": {}
  "/rooms/[slug]": { "slug": string; }
  "/seo/[slug]": { "slug": string; }
  "/start": {}
  "/terms": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin-gate": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
