// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin-gate/cms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-gate/cms">> = Specific
  const handler = {} as typeof import("../../app/admin-gate/cms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin-gate/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-gate/login">> = Specific
  const handler = {} as typeof import("../../app/admin-gate/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin-gate/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin-gate">> = Specific
  const handler = {} as typeof import("../../app/admin-gate/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/bookings">> = Specific
  const handler = {} as typeof import("../../app/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/analytics">> = Specific
  const handler = {} as typeof import("../../app/dashboard/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/automation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/automation">> = Specific
  const handler = {} as typeof import("../../app/dashboard/automation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/billing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/billing">> = Specific
  const handler = {} as typeof import("../../app/dashboard/billing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/bookings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/content-generator/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/content-generator">> = Specific
  const handler = {} as typeof import("../../app/dashboard/content-generator/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/cta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/cta">> = Specific
  const handler = {} as typeof import("../../app/dashboard/cta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/leads">> = Specific
  const handler = {} as typeof import("../../app/dashboard/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/media/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/media">> = Specific
  const handler = {} as typeof import("../../app/dashboard/media/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/navigation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/navigation">> = Specific
  const handler = {} as typeof import("../../app/dashboard/navigation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/pages/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pages/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/dashboard/pages/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/pages/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pages/new">> = Specific
  const handler = {} as typeof import("../../app/dashboard/pages/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/pages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/pages">> = Specific
  const handler = {} as typeof import("../../app/dashboard/pages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/seo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/seo">> = Specific
  const handler = {} as typeof import("../../app/dashboard/seo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/settings">> = Specific
  const handler = {} as typeof import("../../app/dashboard/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/tenants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/tenants">> = Specific
  const handler = {} as typeof import("../../app/dashboard/tenants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/theme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/theme">> = Specific
  const handler = {} as typeof import("../../app/dashboard/theme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/elite/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/elite/dashboard">> = Specific
  const handler = {} as typeof import("../../app/elite/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/elite/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/elite/login">> = Specific
  const handler = {} as typeof import("../../app/elite/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/elite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/elite">> = Specific
  const handler = {} as typeof import("../../app/elite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/furniture/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/furniture/[type]">> = Specific
  const handler = {} as typeof import("../../app/furniture/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/furniture/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/furniture">> = Specific
  const handler = {} as typeof import("../../app/furniture/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/pages/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pages/[slug]">> = Specific
  const handler = {} as typeof import("../../app/pages/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/request">> = Specific
  const handler = {} as typeof import("../../app/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/room/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/room/[id]">> = Specific
  const handler = {} as typeof import("../../app/room/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rooms/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rooms/[slug]">> = Specific
  const handler = {} as typeof import("../../app/rooms/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/rooms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/rooms">> = Specific
  const handler = {} as typeof import("../../app/rooms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/seo/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/seo/[slug]">> = Specific
  const handler = {} as typeof import("../../app/seo/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/start/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/start">> = Specific
  const handler = {} as typeof import("../../app/start/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/analyze-lead/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/analyze-lead">> = Specific
  const handler = {} as typeof import("../../app/api/admin/analyze-lead/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/dev-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/dev-login">> = Specific
  const handler = {} as typeof import("../../app/api/auth/dev-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/recovery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/recovery">> = Specific
  const handler = {} as typeof import("../../app/api/auth/recovery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bookings/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/bookings/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/bookings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/bookings">> = Specific
  const handler = {} as typeof import("../../app/api/bookings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/checkout">> = Specific
  const handler = {} as typeof import("../../app/api/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cms/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cms/config">> = Specific
  const handler = {} as typeof import("../../app/api/cms/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cms/public-config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cms/public-config">> = Specific
  const handler = {} as typeof import("../../app/api/cms/public-config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cms/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cms/upload">> = Specific
  const handler = {} as typeof import("../../app/api/cms/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content-generator/improve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-generator/improve">> = Specific
  const handler = {} as typeof import("../../app/api/content-generator/improve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/content-generator/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/content-generator">> = Specific
  const handler = {} as typeof import("../../app/api/content-generator/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/curate-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curate-images">> = Specific
  const handler = {} as typeof import("../../app/api/curate-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/curated-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curated-images">> = Specific
  const handler = {} as typeof import("../../app/api/curated-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/curated-pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/curated-pages">> = Specific
  const handler = {} as typeof import("../../app/api/curated-pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/enhance-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/enhance-image">> = Specific
  const handler = {} as typeof import("../../app/api/enhance-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media">> = Specific
  const handler = {} as typeof import("../../app/api/media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/navigation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/navigation">> = Specific
  const handler = {} as typeof import("../../app/api/navigation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pages/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pages/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/pages/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pages/[id]/sections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pages/[id]/sections">> = Specific
  const handler = {} as typeof import("../../app/api/pages/[id]/sections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pages">> = Specific
  const handler = {} as typeof import("../../app/api/pages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/pexels/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/pexels">> = Specific
  const handler = {} as typeof import("../../app/api/pexels/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tenant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenant">> = Specific
  const handler = {} as typeof import("../../app/api/tenant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tenants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tenants">> = Specific
  const handler = {} as typeof import("../../app/api/tenants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/theme/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/theme">> = Specific
  const handler = {} as typeof import("../../app/api/theme/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin-gate/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin-gate">> = Specific
  const handler = {} as typeof import("../../app/admin-gate/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
