-- P7-M2: retire the old identity in stored VALUES (no schema change yet).
--
-- The columns come from scanning every text/jsonb column in the live database,
-- not from guessing tables. Where a column holds prose an agent wrote in the
-- past, the chain still rewrites the identity tokens inside it, but the
-- read-back check treats those columns as history and reports what remains
-- instead of failing: a sentence the owner already read is not rewritten to
-- look tidy.
--
-- Snapshots use CREATE TABLE IF NOT EXISTS … AS SELECT so a re-run neither
-- duplicates rows nor breaks on a column added since the first run. Every
-- UPDATE touches only rows that still match, so the file is idempotent.

CREATE TABLE IF NOT EXISTS public._p7_backup_agent_messages AS SELECT * FROM public.agent_messages;
CREATE TABLE IF NOT EXISTS public._p7_backup_agent_profiles AS SELECT * FROM public.agent_profiles;
CREATE TABLE IF NOT EXISTS public._p7_backup_enterprise_agents AS SELECT * FROM public.enterprise_agents;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_benchmark_runs AS SELECT * FROM public.qayyim_benchmark_runs;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_drafts AS SELECT * FROM public.qayyim_drafts;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_experiments AS SELECT * FROM public.qayyim_experiments;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_suggestions AS SELECT * FROM public.qayyim_suggestions;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_swarm_learnings AS SELECT * FROM public.qayyim_swarm_learnings;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_sync_events AS SELECT * FROM public.qayyim_sync_events;
CREATE TABLE IF NOT EXISTS public._p7_backup_qayyim_task_metrics AS SELECT * FROM public.qayyim_task_metrics;
CREATE TABLE IF NOT EXISTS public._p7_backup_agent_conversations AS SELECT * FROM public.agent_conversations;
CREATE TABLE IF NOT EXISTS public._p7_backup_agent_tasks AS SELECT * FROM public.agent_tasks;

UPDATE public.agent_messages
     SET "sender_name" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("sender_name", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "sender_name" ~* 'qayyim|قيّم الدار';
UPDATE public.agent_messages
     SET "context" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("context"::text, 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')::jsonb
   WHERE "context"::text ~* 'qayyim|قيّم الدار';
UPDATE public.agent_profiles
     SET "agent_key" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("agent_key", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "agent_key" ~* 'qayyim|قيّم الدار';
UPDATE public.agent_profiles
     SET "name" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("name", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "name" ~* 'qayyim|قيّم الدار';
UPDATE public.enterprise_agents
     SET "agent_key" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("agent_key", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "agent_key" ~* 'qayyim|قيّم الدار';
UPDATE public.enterprise_agents
     SET "name" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("name", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "name" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_benchmark_runs
     SET "agent_key" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("agent_key", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "agent_key" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_benchmark_runs
     SET "details" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("details"::text, 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')::jsonb
   WHERE "details"::text ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_drafts
     SET "created_by" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("created_by", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "created_by" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_experiments
     SET "created_by" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("created_by", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "created_by" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_suggestions
     SET "source_agent" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("source_agent", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "source_agent" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_swarm_learnings
     SET "source_agent" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("source_agent", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "source_agent" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_sync_events
     SET "source_agent" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("source_agent", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "source_agent" ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_sync_events
     SET "target_agents" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("target_agents"::text, 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')::jsonb
   WHERE "target_agents"::text ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_sync_events
     SET "payload" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("payload"::text, 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')::jsonb
   WHERE "payload"::text ~* 'qayyim|قيّم الدار';
UPDATE public.qayyim_task_metrics
     SET "agent_key" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("agent_key", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "agent_key" ~* 'qayyim|قيّم الدار';
UPDATE public.agent_conversations
     SET "title" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("title", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "title" ~* 'qayyim|قيّم الدار';
UPDATE public.agent_tasks
     SET "description" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("description", 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')
   WHERE "description" ~* 'qayyim|قيّم الدار';
UPDATE public.agent_tasks
     SET "output_data" = replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace("output_data"::text, 'qayyim-core', 'ops-lead'), 'qayyim-cont', 'ops-content'), 'qayyim-vis', 'ops-visual'), 'qayyim-seo', 'ops-seo'), 'qayyim-ux', 'ops-ux'), 'qayyim-ana', 'ops-analytics'), 'qayyim-dev', 'ops-dev'), 'qayyim-qa', 'ops-qa'), 'QAYYIM-CORE', 'OPS-LEAD'), 'QAYYIM-CONT', 'OPS-CONTENT'), 'QAYYIM-VIS', 'OPS-VISUAL'), 'QAYYIM-SEO', 'OPS-SEO'), 'QAYYIM-UX', 'OPS-UX'), 'QAYYIM-ANA', 'OPS-ANALYTICS'), 'QAYYIM-DEV', 'OPS-DEV'), 'QAYYIM-QA', 'OPS-QA'), 'qayyim_whoami', 'ops_self'), 'qayyim_world', 'ops_world'), 'qayyim_rivals', 'ops_rivals'), 'qayyim_forecast', 'ops_forecast'), 'qayyim_luxury_score', 'ops_luxury_score'), 'qayyim_goals_risk', 'ops_goals_risk'), 'قيّم الدار - القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار — القائد', 'مدير تشغيل المحتوى'), 'قيّم الدار - المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار — المحتوى والعربية', 'وكيل المحتوى'), 'قيّم الدار - المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار — المرئي والصور', 'وكيل المرئيات'), 'قيّم الدار - الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار — الظهور والبحث', 'وكيل الظهور'), 'قيّم الدار - تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار — تجربة المستخدم', 'وكيل التجربة'), 'قيّم الدار - التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار — التحليلات والأعمال', 'وكيل التحليلات'), 'قيّم الدار - التطوير', 'وكيل التطوير'), 'قيّم الدار — التطوير', 'وكيل التطوير'), 'قيّم الدار - الجودة والاختبار', 'وكيل الجودة'), 'قيّم الدار — الجودة والاختبار', 'وكيل الجودة')::jsonb
   WHERE "output_data"::text ~* 'qayyim|قيّم الدار';

NOTIFY pgrst, 'reload schema';
