var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/rooms/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__08xj1d2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_060d1m.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ixdcs~._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0h5tz8r._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0f3d_nc.js")
R.c("server/chunks/ssr/[root-of-the-server]__10914~~._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0.angw.._.js")
R.c("server/chunks/ssr/node_modules_100_dhq._.js")
R.c("server/chunks/ssr/_0gyit03._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_rooms_[slug]_page_actions_0jlbq0-.js")
R.m(2670)
module.exports=R.m(2670).exports
